name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
      - name: Build with Maven
        run: mvn --global-toolchains toolchains.xml -B package --file pom.xml

      - name: Run Helper
        id: helper
        run: "chmod +x ./.github/release-helper && bash ./.github/release-helper"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Artifact Directory
        run: "mkdir ./artifacts"

      - name: Find and Move JARS
        run: "mv `find target -name *.jar -print` ./artifacts"

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: Artifacts
          path: "./artifacts"
