on:
  push:
    tags:
      - 'v*.*.*'

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Helper
        id: helper
        run: "chmod +x ./.github/release-helper && bash ./.github/release-helper"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord Success Message
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#32cd32"
          message: "**[${{ GITHUB_REPOSITORY }} - Build ${{ GITHUB_RUN_ID }}]**\n\nBuild Success!\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"

      - name: Discord Failure Message
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#f70d1a"
          message: "**[${{ GITHUB_REPOSITORY }} - Build ${{ GITHUB_RUN_ID }}]**\n\nBuild Failed!\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"

      - name: Make Artifact Directory
        run: "mkdir ./artifacts"

      - name: Find and Move JARS
        run: "mv `find target -name *.jar -print` ./artifacts"

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: Artifacts
          path: "./artifacts"

      - name: Create Release
        id: create_release
        if: success()
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ GITHUB_RUN_ID }}
          release_name: Build ${{ GITHUB_RUN_ID }}
          draft: false
          prerelease: false

      - name: Discord Success Message
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#32cd32"
          message: "**[${{ GITHUB_REPOSITORY }} - Build ${{ GITHUB_RUN_ID }}]**\nNew Release!\n\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"
